export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const REFRESH_TOKEN = "REFRESH_TOKEN";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SET_COURSES_LIST = "SET_COURSES_LIST";
export const CLEAR_COURSES_LIST = "CLEAR_COURSES_LIST";

export const SET_CURRENT_COURSE = "SET_CURRENT_COURSE";
export const CLEAR_CURRENT_COURSE = "CLEAR_CURRENT_COURSE";

export const SET_COURSETOPICS_LIST = "SET_COURSETOPICS_LIST";
export const CLEAR_COURSETOPICS_LIST = "CLEAR_COURSETOPICS_LIST";
