# Generated by Django 4.0.1 on 2022-01-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['courseName']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='reviews',
        ),
    ]
