# Generated by Django 4.0.1 on 2022-01-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subtopics',
        ),
    ]
