# Generated by Django 4.0.1 on 2022-01-29 11:10

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_course_duration_course_enrolledstudents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('formula', models.TextField(blank=True)),
                ('orderno', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='orderno',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('orderno', models.IntegerField(default=0)),
                ('about', models.TextField()),
                ('description', models.TextField()),
                ('video_url', models.CharField(max_length=1000)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'ordering': ['topic'],
            },
        ),
        migrations.CreateModel(
            name='ModelQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('orderno', models.IntegerField(default=0)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('answer', models.TextField()),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='course.subtopic')),
            ],
            options={
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='FAQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('orderno', models.IntegerField(default=0)),
                ('answer', models.TextField()),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='course.subtopic')),
                ('user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('reviewText', models.TextField()),
                ('rating', models.IntegerField()),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['headline'],
            },
        ),
    ]
